In [3]:
import numpy as np
import pandas as pd

# CREATING DATAFRAMES 
___

In [1]:
# data frames id always is created  using a dictionary 
d = {'Name':['Ram','Sita', 'Gita','Hari', 'Shyam'],
     'Roll': [111,222,333,444,555],
     'Course': ['AIML', 'Python', 'AIML','C', 'Java'] }
d

{'Name': ['Ram', 'Sita', 'Gita', 'Hari', 'Shyam'],
 'Roll': [111, 222, 333, 444, 555],
 'Course': ['AIML', 'Python', 'AIML', 'C', 'Java']}

In [44]:
df = pd.DataFrame(d)
df

    Name  Roll  Course
0    Ram   111    AIML
1   Sita   222  Python
2   Gita   333    AIML
3   Hari   444       C
4  Shyam   555    Java

In [5]:
type(df)

pandas.core.frame.DataFrame

In [8]:
# Indexing
df.Name[3]

'Hari'

In [9]:
df.Course[0]

'AIML'

In [19]:
# Slicing 
# iloc- used for slicing onn DataFrames
# syntax: df.iloc[row_slicing, column_slicing]
df.iloc[1,::]
df.iloc[::,2]
df.iloc[::2,::] 
df.iloc[1::2, ::2]

   Name  Course
1  Sita  Python
3  Hari       C

In [ ]:
# head = it represents the top rows of the data frame
df.head(2)
df.head() # it used to by default first 5 rows

   Name  Roll  Course
0   Ram   111    AIML
1  Sita   222  Python

In [23]:
# tail= it represents the bottom rows of the data frame
df.tail(3)

    Name  Roll Course
2   Gita   333   AIML
3   Hari   444      C
4  Shyam   555   Java

In [26]:
# sample = it returns random sample from the dataframe
df.sample()

   Name  Roll Course
3  Hari   444      C

In [33]:
# rename 
df = df.rename(columns={'Name': 'Stu_Name'})
df

  Stu_Name  Roll  Course
0      Ram   111    AIML
1     Sita   222  Python
2     Gita   333    AIML
3     Hari   444       C
4    Shyam   555    Java

In [52]:
# set index = can set any column as index position
#df.df.set_index('Roll')
# df.set_index('Roll', inplace= True)
# df.set_index('Roll',inplace=True)
df.set_index('Roll',inplace=True)

In [54]:

df.reset_index()

   Roll   Name  Course
0   111    Ram    AIML
1   222   Sita  Python
2   333   Gita    AIML
3   444   Hari       C
4   555  Shyam    Java

In [57]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'Days':[1,2,3,4,5],  
                   'Places':['Puri', 'Mathura', 'Asansol','Manali','Kolkata'],
                   'Visitors':[5895,5600,4859, 5000, 5800] })
df

   Days   Places  Visitors
0     1     Puri      5895
1     2  Mathura      5600
2     3  Asansol      4859
3     4   Manali      5000
4     5  Kolkata      5800

In [62]:
# to check missing value
df.isnull()
# isnull().sum() is used to count the number of false or true
df.isnull().sum()

Days        0
Places      0
Visitors    0
dtype: int64

In [65]:
df = pd.DataFrame({'Days':[1,2,3,4,5],  
                   'Places':['Puri', 'Mathura', np.nan,'Manali','Kolkata'],
                   'Visitors':[5895,5600,4859, 5000, 5800] })
df
df.isnull()

    Days  Places  Visitors
0  False   False     False
1  False   False     False
2  False    True     False
3  False   False     False
4  False   False     False

In [ ]:
# import warnings 
# warnings.filterwarnings('ignore')

In [69]:
# fillna = to fill null value
df.Places.fillna('Puri')
df.Places.fillna('Puri',inplace=True)
df

   Days   Places  Visitors
0     1     Puri      5895
1     2  Mathura      5600
2     3     Puri      4859
3     4   Manali      5000
4     5  Kolkata      5800

In [70]:
# to check data types of all columns 
df.dtypes

Days         int64
Places      object
Visitors     int64
dtype: object

In [71]:
# info = to get short information about the data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Days      5 non-null      int64
 1   Places    5 non-null      object
 2   Visitors  5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [72]:
# unique 
df.Places.unique()

array(['Puri', 'Mathura', 'Manali', 'Kolkata'], dtype=object)

In [74]:
df.Visitors.mean()

np.float64(5430.8)

In [75]:
df.Visitors.std()

472.48354468700813

In [77]:
df.Visitors.max()

5895

In [ ]:
# describe  returns the statistical calculation of the data frame``
df.describe()

           Days     Visitors
count  5.000000     5.000000
mean   3.000000  5430.800000
std    1.581139   472.483545
min    1.000000  4859.000000
25%    2.000000  5000.000000
50%    3.000000  5600.000000
75%    4.000000  5800.000000
max    5.000000  5895.000000

In [80]:
df.describe(include= 'all') # include is use to include

            Days Places     Visitors
count   5.000000      5     5.000000
unique       NaN      4          NaN
top          NaN   Puri          NaN
freq         NaN      2          NaN
mean    3.000000    NaN  5430.800000
std     1.581139    NaN   472.483545
min     1.000000    NaN  4859.000000
25%     2.000000    NaN  5000.000000
50%     3.000000    NaN  5600.000000
75%     4.000000    NaN  5800.000000
max     5.000000    NaN  5895.000000

In [ ]:
df.describe(include='O')

       Places
count       5
unique      4
top      Puri
freq        2

In [9]:
# iris dataset 
import numpy as np
import pandas as pd
iris = pd.read_csv(r"C:\Users\ksaby\Downloads\iris\iris.data")
iris
iris = pd.read_csv(r"C:\Users\ksaby\Downloads\iris\iris.data", header=None)
iris
iris.columns = ['SL','SW','PL','PW', 'FLOWER TYPE']
iris

      SL   SW   PL   PW     FLOWER TYPE
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]